### ISSUE TITLE
 error: unknown type name 'u_char'; did you mean 'char'?

### ISSUE THREAD

**Issue by Xiaoyuyexi** [lparam/xsocks#1]
CC src/signal.o
src/signal.c:18:19: error: unknown type name 'u_char'; did you mean 'char'?
read_file(int fd, u_char *buf, size_t size, off_t offset) {
                  ^~~~~~
                  char
src/signal.c:31:5: error: use of undeclared identifier 'u_char'
    u_char    buf[10];
    ^
src/signal.c:40:23: error: use of undeclared identifier 'buf'
    n = read_file(fd, buf, 10, 0);
                      ^
src/signal.c:48:20: error: use of undeclared identifier 'buf'
    while (n-- && (buf[n] == CR || buf[n] == LF)) { /* void */ }
                   ^
src/signal.c:48:36: error: use of undeclared identifier 'buf'
    while (n-- && (buf[n] == CR || buf[n] == LF)) { /* void */ }
                                   ^
src/signal.c:50:30: error: use of undeclared identifier 'buf'
    return atoi((const char*)buf);
                             ^
6 errors generated.
make: *** [src/signal.o] Error 1

cc -v
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix

**Comment by lparam** [comment]
i have not tested on ios.
just linux and openwrt trunk.
pull request welcome:)
