### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [lparam/xsocks#11]
I would like to point out that identifiers like "[`_COMMON_H`](https://github.com/lparam/xsocks/blob/9e633be0e9518a217359ab23d11aa5f39ea779a3/src/common.h#L1)" and "[`_RESOLVER_H`](https://github.com/lparam/xsocks/blob/84d8e28fcae6a613c9de8604873d83e7745cf787/src/resolver.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by lparam** [comment]
thanks.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/lparam/xsocks/commit/3854a504016180dcfa7a15d97ec68a68987fbd7d "Deletion of a few underscores").
