### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [lparam/xsocks#12]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [create_query_task](https://github.com/lparam/xsocks/blob/8c1ca15c5e0873bed28ac5938af6cb9216217008/src/resolver.c#L80)
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output.") ⇒ [print_buffer](https://github.com/lparam/xsocks/blob/8c1ca15c5e0873bed28ac5938af6cb9216217008/src/util.c#L16)

**Comment by lparam** [comment]
I think it is not necessary in these cases.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by lparam** [comment]
It could take sometime. if you have time and feel like to providing a patch or pull request that's always welcome.

**Comment by elfring** [comment]
Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by lparam** [comment]
No plan for this.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for your software?
