### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [lparam/xsocks#13]
I suggest to reuse a higher level build system than [your current make file](https://github.com/lparam/xsocks/blob/9e633be0e9518a217359ab23d11aa5f39ea779a3/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](http://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by lparam** [comment]
I like keep makefile simply clean.
