### ISSUE TITLE
Can not compile 0.3.0 for openwrt

### ISSUE THREAD

**Issue by debiansid** [lparam/xsocks#14]
In file included from src/acl.c:6:0:
3rd/libipset/include/ipset/ipset.h:16:26: fatal error: libcork/core.h: No such file or directory
 #include <libcork/core.h>
                          ^
compilation terminated.
make[3]: *** [src/acl.o] Error 1
make[3]: Leaving directory `/data/ezhang/openwrt/build_dir/target-i386_i486_uClibc-0.9.33.2/xsocks-0.3.0'
make[2]: *** [/data/ezhang/openwrt/build_dir/target-i386_i486_uClibc-0.9.33.2/xsocks-0.3.0/.built] Error 2
make[2]: Leaving directory `/data/ezhang/openwrt/package/xsocks/openwrt'
make[1]: *** [package/xsocks/openwrt/compile] Error 2
make[1]: Leaving directory `/data/ezhang/openwrt'
make: *** [package/xsocks/openwrt/compile] Error 2

**Comment by debiansid** [comment]
looks like libcork directory is not in right structure

**Comment by lparam** [comment]
fixed on 0.3.1
