### ISSUE TITLE
Debian7 64bit,openwrt x86 compile.

### ISSUE THREAD

**Issue by godwasdog** [lparam/xsocks#2]
make package/xsocks/openwrt/compile V=99
#
# configuration written to .config
#
make[1]: Entering directory `/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2'
make[2]: Entering directory `/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/package/xsocks/openwrt'
CFLAGS="-Os -pipe -march=i486 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable  -I/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/include -I/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/target-i386_i486_uClibc-0.9.33.2/include -I/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/include " CXXFLAGS="-Os -pipe -march=i486 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable  -I/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/include -I/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/target-i386_i486_uClibc-0.9.33.2/include -I/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/include " LDFLAGS="-L/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/lib -L/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/target-i386_i486_uClibc-0.9.33.2/lib -L/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/lib " make -j1 -C /home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-i386_i486_uClibc-0.9.33.2/xsocks-0.1.2/. AR=i486-openwrt-linux-uclibc-ar AS="ccache_cc -c -Os -pipe -march=i486 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable" LD=i486-openwrt-linux-uclibc-ld NM=i486-openwrt-linux-uclibc-nm CC="ccache_cc" GCC="ccache_cc" CXX="ccache_cxx" RANLIB=i486-openwrt-linux-uclibc-ranlib STRIP=i486-openwrt-linux-uclibc-strip OBJCOPY=i486-openwrt-linux-uclibc-objcopy OBJDUMP=i486-openwrt-linux-uclibc-objdump SIZE=i486-openwrt-linux-uclibc-size CROSS="i486-openwrt-linux-uclibc-" ARCH="i386" ;
make[3]: Entering directory `/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-i386_i486_uClibc-0.9.33.2/xsocks-0.1.2'
cd 3rd/libuv && ./autogen.sh && ./configure --host=i486-openwrt-linux-uclibc LDFLAGS= && make
+ libtoolize
/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/target-i386_i486_uClibc-0.9.33.2/host/bin/libtoolize: 1: /home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/target-i386_i486_uClibc-0.9.33.2/host/bin/libtoolize: /BB/build/x86/generic/staging_dir/host/bin/sed: not found
/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/target-i386_i486_uClibc-0.9.33.2/host/bin/libtoolize: 1: /home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/target-i386_i486_uClibc-0.9.33.2/host/bin/libtoolize: /BB/build/x86/generic/staging_dir/host/bin/sed: not found
: $pkgltdldir is not a directory: `/BB/build/x86/generic/staging_dir/target-i386_i486_uClibc-0.9.33.2/host/share/libtool'
make[3]: *** [3rd/libuv/Makefile] Error 1
make[3]: Leaving directory `/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-i386_i486_uClibc-0.9.33.2/xsocks-0.1.2'
make[2]: *** [/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-i386_i486_uClibc-0.9.33.2/xsocks-0.1.2/.built] Error 2
make[2]: Leaving directory `/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/package/xsocks/openwrt'
make[1]: *** [package/xsocks/openwrt/compile] Error 2
make[1]: Leaving directory `/home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2'
make: *** [package/xsocks/openwrt/compile] 错误 2

**Comment by lparam** [comment]
1. sudo apt-get install ccache
2. sudo mkdir /BB && sudo mkdir /BB/build && sudo mkdir /BB/build/x86
3. sudo ln -s /home/openwrt/OpenWrt-SDK-x86-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2 /BB/build/x86/generic
4. make package/xsocks/openwrt/compile V=99

**Comment by wzc0x0** [comment]
主要问题在创建连接符号将这个pkgltdldir is not a directory后面缺少的补齐就行了
