### ISSUE TITLE
哪里有xSocks的exe文件下载？

### ISSUE THREAD

**Issue by luckypoem** [lparam/xSocks#20]
在https://github.com/lparam/xSocks没看到

**Comment by luckypoem** [comment]
哦，看到了：Windows客户端-
https://github.com/lparam/xSocks-windows/releases/download/v1.1.3/Xsocks.exe

**Comment by TheCalling** [comment]
@lparam 请问，%appdata%\local\{F8C544A4-D4FF-41B8-A74C-BE922EFA34F2}(配置文件)可否默认生成在xSocks.exe同一目录下面？

**Comment by lparam** [comment]
没必要 现在的做法是windows上的通行惯例

mervin <notifications@github.com>于2016年5月6日周五 11:01写道：

**Comment by TheCalling** [comment]
希望xsocks有类似shadowsocks的便携模式，请问修改源码哪里，可达成效果，我试着去编译一下。谢谢

**Comment by lparam** [comment]
往程序目录放东西要考虑权限等别的东西 如果你真需要这个feature 自己fork一个改改看 代码量很少 但我不保证会merge

mervin <notifications@github.com>于2016年5月7日周六 08:54写道：

**Comment by lparam** [comment]
另外，这是xSocks-windows项目的问题，issue应该往那边发。
