### ISSUE TITLE
在mac下，make失败，如何解决？

### ISSUE THREAD

**Issue by luckypoem** [lparam/xSocks#21]
hi。

yudeMacBook-Air:xSocks brite$ make
    LINK xSocksd
clang: warning: argument unused during compilation: '-pthread'
ld: unknown option: --gc-sections
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/yuming/xsocks/xSocksd] Error 1
yudeMacBook-Air:xSocks brite$

**Comment by luckypoem** [comment]
感觉在windows下，蛮好用。能否提供一个像shadowsocksX-2.6.3.dmg那样的mac下的客户端程序呢？

**Comment by lparam** [comment]
我手上没有mac机器，你可以尝试一下修改Makefile，把 --gc-sections选项注释掉再编译看看。

**Comment by luckypoem** [comment]
hi.我把 --gc-sections选项注释掉了，再编译还是出错，如何解决？

...
acountry.c:276:22: warning: illegal character encoding in string literal
      [-Winvalid-source-encoding]
       { 248, "ax", "<C5>land Island"                         },
                     ^~~~
1 warning generated.
libtool: link: gcc -Qunused-arguments -g0 -Os -o acountry acountry-acountry.o acountry-ares_getopt.o acountry-ares_nowarn.o acountry-ares_strcasecmp.o  ./.libs/libcares.a
    CC src/util.o
    CC src/logger.o
    CC src/common.o
    CC src/crypto.o
    CC src/resolver.o
    CC src/daemon.o
    CC src/signal.o
    CC src/consumer.o
    CC src/cache.o
    CC src/packet.o
    CC src/xSocksd_udprelay.o
    CC src/xSocksd_client.o
    CC src/xSocksd_remote.o
    CC src/xSocksd.o
    LINK xSocksd
clang: warning: argument unused during compilation: '-pthread'
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/yuming/xSocks/xSocksd] Error 1
yudeMacBook-Air:xSocks brite$

**Comment by luckypoem** [comment]
搜索了一下，找到2篇文章，但未看懂。
http://blog.csdn.net/ioswyl88219/article/details/21455573
http://www.cnblogs.com/zhulin/archive/2011/12/04/2275205.html

还请指点一下。

**Comment by lparam** [comment]
我建议你放弃在mac上使用，因为我没有考虑过兼容mac。
如果有条件，建议你在网关上部署(建议使用 [xTun](https://github.com/lparam/xTun))，这是最好的使用方法。
