### ISSUE TITLE
我在一台vps上编译成功，在另一台上编译失败，如何解决？

### ISSUE THREAD

**Issue by luckypoem** [lparam/xSocks#22]
hi.
...
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:549: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
make: *** [/root/xSocks/3rd/libsodium/Makefile] 错误 1
root@AR:~/xSocks#

非常感谢

**Comment by luckypoem** [comment]
建议在debian8下安装,我在debian8下安装成功！在centos7,debian7,ubuntu14.04下，都安装失败。

**Comment by lparam** [comment]
我在ubuntu14.04下不能重现上面的错误，请查检你的系统上面的libtool等相关工具是否已经安装并正常工作。

**Comment by luckypoem** [comment]
hi.
xsocks在windows下的客户端的端口号默认为1081吗？如何修改xsocks在windows下的客户端的端口号？

**Comment by sendmail** [comment]
用的debian7遇到同样的问题

**Comment by luckypoem** [comment]
hi.
“autoreconf: /usr/bin/autoconf failed with exit status: 1”透露了出错的关键所在。
运行apt-cache search autoreconf
在展示的结果中，选择安装dh-autoreconf 。
运行apt-get install dh-autoreconf -y即可解决问题。

**Comment by lparam** [comment]
@luckypoem 端口写在代码里了，程序会自己找一个合适的端口使用，不一定是1081，用户不需要修改。
