### ISSUE TITLE
好多vps的核心还是2.6啊，SO_REUSEPORT选项出错

### ISSUE THREAD

**Issue by godwasdog** [lparam/xsocks#3]
error: 'SO_REUSEPORT' undeclared (first use in this function)
 note: each undeclared identifier is reported only once for each function it appears in

好多vps的核心还是2.6啊，SO_REUSEPORT选项出错
http://stackoverflow.com/questions/3261965/so-reuseport-on-linux

我暂时用15代替编译成功，不知道行不行

**Comment by LazyZhu** [comment]
Try `SO_REUSEADDR` instead of `SO_REUSEPORT`

**Comment by lparam** [comment]
SO_REUSEADDR can not instead of SO_REUSEPORT
