### ISSUE TITLE
listen port of server 

### ISSUE THREAD

**Issue by angusding** [lparam/xsocks#4]
I want to know the port number used by server end for configure firewall.
Would you please tell me how can I get it?

**Comment by lparam** [comment]
default port: 1073

>>>xsocksd --help

Usage: xsocksd [-l bind] <-k password> [-p pidfile] [-c concurrency] [-t timeout] [-s signal] [-nhvV]

Options:
-k <password> : password of server
[-l <bind address>] : bind address:port (default: 0.0.0.0:1073)
[-c <concurrency>] : worker threads
[-d <dns>] : name servers for internal DNS resolver
[-p <pidfile>] : pid file path (default: /var/run/xsocks/xsocksd.pid)
[-t <timeout>] : connection timeout in senconds
[--signal <signal>] : send signal to xsocksd: quit, stop
[-n] : non daemon mode
[-h, --help] : this help
[-v, --version] : show version
[-V] : verbose mode
