### ISSUE TITLE
Error of make

### ISSUE THREAD

**Issue by angusding** [lparam/xsocks#5]
In file included from src/xtproxy_client.c:7:
/usr/include/linux/netfilter_ipv4.h:53: error: 'INT_MIN' undeclared here (not in a function)
/usr/include/linux/netfilter_ipv4.h:64: error: 'INT_MAX' undeclared here (not in a function)
make: *** [src/xtproxy_client.o] Error 1

**Comment by lparam** [comment]
what's you compile environment?
try add "#include <limits.h>"  before #include <linux/netfilter_ipv4.h> .

**Comment by angusding** [comment]
centos6.5 and OpenVZ VPS.

**Comment by lparam** [comment]
try add "#include \<limits.h\>" before "#include \<netfilter_ipv4.h\>".

**Comment by angusding** [comment]
It's ok after add "#include <limits.h>" at line 6 in the file "src/xtproxy_client.c". I have to add comments at lines related "xtproxy"  in the file "Makefile" before get your solution.
Now close this issues.
