### ISSUE TITLE
Error infomation of making xsocks v0.1.6

### ISSUE THREAD

**Issue by angusding** [lparam/xsocks#6]
New issue found during making xsocks v0.1.6, but no problem found in v0.1.5.
I also found many wanning about libtool. Would you please tell me the lowest version of libtool requested? 
Error infomation:
    CC src/daemon.o
    CC src/signal.o
    CC src/consumer.o
    CC src/cache.o
    CC src/packet.o
    CC src/xsocksd_udprelay.o
    CC src/xsocksd_client.o
    CC src/xsocksd_remote.o
    CC src/xsocksd.o
    LINK xsocksd
3rd/libuv/.libs/libuv.a(libuv_la-linux-core.o): In function `uv_uptime':
/home/openwrt/tmp/xsocks/3rd/libuv/src/unix/linux-core.c:499: undefined reference to `clock_gettime'
/home/openwrt/tmp/xsocks/3rd/libuv/src/unix/linux-core.c:501: undefined reference to `clock_gettime'
3rd/libuv/.libs/libuv.a(libuv_la-linux-core.o): In function `uv__hrtime':
/home/openwrt/tmp/xsocks/3rd/libuv/src/unix/linux-core.c:384: undefined reference to `clock_gettime'
/home/openwrt/tmp/xsocks/3rd/libuv/src/unix/linux-core.c:372: undefined reference to `clock_getres'
3rd/c-ares/.libs/libcares.a(libcares_la-ares__timeval.o): In function `ares__tvnow':
ares__timeval.c:(.text+0x19): undefined reference to `clock_gettime'
collect2: ld returned 1 exit status
make: *** [xsocksd] Error 1

**Comment by lparam** [comment]
v0.16 just add android ndk build script and remove some comment.
try modify "LDFLAGS += -pthread -ldl" to "LDFLAGS += -pthread -ldl" in Makefile.

**Comment by lparam** [comment]
issue fixed on develop branch.
thanks.
