### ISSUE TITLE
Issues of xsocksd and xtunnel

### ISSUE THREAD

**Issue by angusding** [lparam/xsocks#7]
OS: CentOS 6.4 
1. The options of "-p pidfile" is not effective on xsocksd but effective on xtunnel.
So I have to mkdir the directory /var/run/xsocks.
2. The options of "-s signal/--signal <signal>" is not effective on xtunnel but effective on xsocksd.
So I have to kill its process to stop ti.
3. Some options of usage maybe need "<>" like "-p" and "-s" (xtunnel) .

**Comment by lparam** [comment]
1. /var/run/xsocks is the default path, Normally, you have create the directory like:
  sudo mkdir /var/run/xsocks && chown LoginName:Group /var/run/xsocks
. xsocksd -p option works fine on my machine. what's the log output?
2. fixed on develop branch.
3. -p don't need <>, xtunnel -s change to xtunnel --signal now.

**Comment by angusding** [comment]
I want to set pidfile to my custom path(/var/run) for xsocksd and xtunnel. but no effective after set it in scripts.

**Comment by lparam** [comment]
/var/run need root permission

**Comment by angusding** [comment]
My shadwosocks server starting as nobody user but it can create pid file and log file by root user.
So I think it will be all right if I change default directory for pid file.

**Comment by lparam** [comment]
Don't put the PID file in /var/run/foo.pid
http://serverfault.com/questions/197716/how-can-i-drop-privileges-and-still-clean-up-my-pid-file-in-var-run
