### ISSUE TITLE
0.1.6 compile error on centos

### ISSUE THREAD

**Issue by debiansid** [lparam/xsocks#9]
CC src/util.o
src/util.c: In function ‘resolve_addr’:
src/util.c:153: warning: dereferencing pointer ‘addr6.15’ does break strict-aliasing rules
src/util.c:153: note: initialized from here
    CC src/logger.o
    CC src/crypto.o
    CC src/resolver.o
src/resolver.c: In function ‘query_cb’:
src/resolver.c:142: warning: dereferencing pointer ‘addr4’ does break strict-aliasing rules
src/resolver.c:141: warning: dereferencing pointer ‘addr4’ does break strict-aliasing rules
src/resolver.c:140: warning: dereferencing pointer ‘addr4’ does break strict-aliasing rules
src/resolver.c:139: note: initialized from here
src/resolver.c:148: warning: dereferencing pointer ‘addr6’ does break strict-aliasing rules
src/resolver.c:147: warning: dereferencing pointer ‘addr6’ does break strict-aliasing rules
src/resolver.c:146: warning: dereferencing pointer ‘addr6’ does break strict-aliasing rules
src/resolver.c:145: note: initialized from here
    CC src/daemon.o
    CC src/signal.o
    CC src/consumer.o
    CC src/cache.o
    CC src/packet.o
    CC src/xsocksd_udprelay.o
    CC src/xsocksd_client.o
    CC src/xsocksd_remote.o
    CC src/xsocksd.o
    LINK xsocksd
3rd/libuv/.libs/libuv.a(libuv_la-linux-core.o): In function `uv_uptime':
/data/ezhang/xsocks/3rd/libuv/src/unix/linux-core.c:501: undefined reference to `clock_gettime'
/data/ezhang/xsocks/3rd/libuv/src/unix/linux-core.c:499: undefined reference to `clock_gettime'
3rd/libuv/.libs/libuv.a(libuv_la-linux-core.o): In function `uv__hrtime':
/data/ezhang/xsocks/3rd/libuv/src/unix/linux-core.c:384: undefined reference to `clock_gettime'
/data/ezhang/xsocks/3rd/libuv/src/unix/linux-core.c:372: undefined reference to `clock_getres'
3rd/c-ares/.libs/libcares.a(libcares_la-ares__timeval.o): In function `ares__tvnow':
ares__timeval.c:(.text+0xf): undefined reference to `clock_gettime'
collect2: ld returned 1 exit status
make: *** [xsocksd] Error 1

**Comment by lparam** [comment]
duplicate with #6
